In [ ]:
##TENSORFLOW

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.constant([[1,3],
                [2,4]])
b = tf.constant([[1,1],
                [2,2]])

In [4]:
print(a+b)

tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32)


In [7]:
x = np.random.rand(100).astype(np.float32)
print(x)

[0.9511424  0.6716715  0.46364066 0.51816875 0.5231936  0.31079033
 0.79599583 0.20089975 0.3288255  0.91914743 0.65311855 0.33584005
 0.31085727 0.61967164 0.6639311  0.98187274 0.10661719 0.96592945
 0.5627306  0.4407569  0.85769415 0.2839393  0.01241841 0.91036266
 0.6545728  0.00255433 0.67514026 0.84835523 0.5079594  0.779866
 0.8927157  0.44742498 0.19351995 0.9010664  0.5236787  0.31202963
 0.4242046  0.2740743  0.25660667 0.23209159 0.5485522  0.4324749
 0.91290367 0.31219262 0.8249075  0.44079897 0.62256587 0.2685203
 0.13385305 0.19119361 0.41266456 0.2965987  0.65892196 0.69477206
 0.34241843 0.6376019  0.50726587 0.5769622  0.00291623 0.14870653
 0.4415439  0.02774359 0.49920368 0.2887906  0.5838207  0.51246107
 0.9819332  0.17887723 0.6815182  0.68112224 0.96316314 0.10740443
 0.26265085 0.39006793 0.3226052  0.5385419  0.14844078 0.43531644
 0.76240844 0.5910943  0.08721524 0.60043913 0.1865538  0.0669349
 0.6575248  0.7580724  0.05379631 0.08393014 0.01414403 0.09044024


In [9]:
y = x*0.2+0.2
w = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

In [11]:
def mse_loss():
    y_pred = w*x+b
    loss = tf.reduce_mean(tf.square(y_pred-y))
    return loss

In [13]:
optimizer = tf.keras.optimizers.Adam()

In [14]:
for step in range(5000):
    optimizer.minimize(mse_loss,var_list=[w,b])
    if step%500 == 0:
        print(step,w.numpy(),b.numpy())


0 [-0.70213014] [0.7751984]
500 [-0.14732446] [0.40566307]
1000 [0.12366103] [0.24487804]
1500 [0.19191621] [0.20475057]
2000 [0.19965617] [0.20020206]
2500 [0.19999534] [0.20000273]
3000 [0.19999912] [0.20000052]
3500 [0.19999935] [0.2000004]
4000 [0.19999948] [0.20000032]
4500 [0.19999963] [0.20000023]


In [15]:
##KERAS

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd

In [2]:
df = pd.read_csv("D:\Deep Learning\Deep Learning - Datasets\diabetes.csv")

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
y = df['Outcome']
x = df.drop(labels=['Outcome'],axis=1)

In [5]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [6]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [7]:
model = Sequential([
    Dense(12,input_shape=(8,),activation='relu'),
    Dense(8,activation='relu'),
    Dense(1,activation='softmax'),
])

In [8]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
H = model.fit(x,y,batch_size=16,epochs=200)

Epoch 1/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5414 - accuracy: 0.3490
Epoch 2/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5359 - accuracy: 0.3490
Epoch 3/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5270 - accuracy: 0.3490
Epoch 4/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5356 - accuracy: 0.3490
Epoch 5/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5306 - accuracy: 0.3490
Epoch 6/200
48/48 [==============================] - 0s 3ms/step - loss: 0.5260 - accuracy: 0.3490
Epoch 7/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5326 - accuracy: 0.3490
Epoch 8/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5254 - accuracy: 0.3490
Epoch 9/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5297 - accuracy: 0.3490
Epoch 10/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5255 - accuracy: 0.3490
Epoch 11/

48/48 [==============================] - 0s 2ms/step - loss: 0.5065 - accuracy: 0.3490
Epoch 84/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4956 - accuracy: 0.3490
Epoch 85/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4917 - accuracy: 0.3490
Epoch 86/200
48/48 [==============================] - 0s 2ms/step - loss: 0.5074 - accuracy: 0.3490
Epoch 87/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4976 - accuracy: 0.3490
Epoch 88/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4932 - accuracy: 0.3490
Epoch 89/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4917 - accuracy: 0.3490
Epoch 90/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4931 - accuracy: 0.3490
Epoch 91/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4957 - accuracy: 0.3490
Epoch 92/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4935 - accuracy: 0.3490
Epoch 93/200


48/48 [==============================] - 0s 2ms/step - loss: 0.4744 - accuracy: 0.3490
Epoch 165/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4725 - accuracy: 0.3490
Epoch 166/200
48/48 [==============================] - 0s 3ms/step - loss: 0.4790 - accuracy: 0.3490
Epoch 167/200
48/48 [==============================] - 0s 3ms/step - loss: 0.4735 - accuracy: 0.3490
Epoch 168/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4770 - accuracy: 0.3490
Epoch 169/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4720 - accuracy: 0.3490
Epoch 170/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4691 - accuracy: 0.3490
Epoch 171/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4702 - accuracy: 0.3490
Epoch 172/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4688 - accuracy: 0.3490
Epoch 173/200
48/48 [==============================] - 0s 2ms/step - loss: 0.4707 - accuracy: 0.3490
Epoc

In [12]:
model.evaluate(x,y)

24/24 [==============================] - 0s 2ms/step - loss: 0.4720 - accuracy: 0.3490


[0.4719836711883545, 0.3489583432674408]

In [13]:
##PYTORCH

In [15]:
!pip install torch

     -------------------------------------- 192.2/192.2 MB 1.9 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\Hp\anaconda3\python.exe -m pip install --upgrade pip' command.


In [18]:
import torch
import numpy as np

In [19]:
data = [[1,2],[2,3]]

In [20]:
print(type(data))
tensor_data = torch.tensor(data)
print(type(tensor_data))

<class 'list'>
<class 'torch.Tensor'>


In [23]:
#using numpy
np_data = np.array(data)
print(type(np_data))
tes_data = torch.tensor(np_data)
print(type(tes_data))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [24]:
new_tensor = torch.ones_like(tensor_data)
print(type(new_tensor))
print(new_tensor)

<class 'torch.Tensor'>
tensor([[1, 1],
        [1, 1]])


In [27]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)

tensor([[0.2960, 0.4282, 0.6730],
        [0.8847, 0.4188, 0.6041]])


In [31]:
tensor_1 = torch.ones(2,3)
tensor_2 = torch.zeros(2,3)
print(tensor_1)
print(tensor_2)
tens=tensor_1.add(4)
print(tens)
tens_1=tensor_2.add(tens)
print(tens_1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])
